weights: resources\models\NK_DAOI_CHIPRC_2\inference\yolo_model.pt
cfg: resources\yamls\yolov5\yolov5s.yaml
data: resources\yamls\yolov5\data.yaml
hyp:
  lr0: 0.01
  lrf: 0.2
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.5
  translate: 0
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.0
  mixup: 0.0
epochs: 3
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: resources\models\NK_DAOI_CHIPRC_2\train\CHIP_RC_Dline_20231228180701
name: yolov5
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 42
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: resources\models\NK_DAOI_CHIPRC_2\train\CHIP_RC_Dline_20231228180701\yolov5
